import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from './app.mjs';
const fixture=handle=>({profile:{id:'me',name:handle,handle,bio:'',color:'#b49aff',avatar:'A',style:'gradient'},posts:[],liked:[],saved:[],follows:[],blocked:[],reports:[],drafts:[],chats:[],assistant:[]});
function client(app){let cookie='';return async(path,body,method=body===undefined?'GET':'POST',origin)=>{const req=new Request('http://localhost:3001/api'+path,{method,headers:{cookie,...(body===undefined?{}:{'content-type':'application/json'}),...(origin?{origin}: {})},...(body===undefined?{}:{body:JSON.stringify(body)})});const res=await app.handle(req);if(res.headers.has('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return {status:res.status,body:await res.json()}}}
async function account(call,name){const r=await call('/auth/register',{email:name+'@example.test',password:'a-strong-test-password'});assert.equal(r.status,200);return r.body.user}
const post=(id,visibility='Public')=>({id,creator:'me',type:'quick',title:'An original moment',text:'',likes:0,comments:[],visibility});
test('authentication, privacy, durable state, conflicts, and logout',async()=>{const app=createApp(),alice=client(app),bob=client(app),anonymous=client(app);try{
 assert.equal((await anonymous('/state')).status,401);const user=await account(alice,'alice');await account(bob,'bob');
 const s=fixture('alice');s.posts=[post('alice-post')];assert.equal((await alice('/state',{revision:0,data:s},'PUT')).status,200);
 assert.equal((await bob('/state')).body.data,null);assert.equal((await alice('/state')).body.data.profile.handle,'alice');
 assert.equal((await alice('/state',{revision:0,data:s},'PUT')).status,409);
 assert.equal((await bob('/feed')).body.posts[0].creator,user.id);
 assert.equal((await alice('/state',{revision:1,data:s},'PUT','https://evil.test')).status,403);
 await alice('/auth/logout',{});assert.equal((await alice('/state')).status,401);
 assert.equal((await alice('/auth/login',{email:'alice@example.test',password:'incorrect-password'})).status,401);
 assert.equal((await alice('/auth/login',{email:'alice@example.test',password:'a-strong-test-password'})).status,200);
 assert.equal((await alice('/state')).body.data.posts[0].id,'alice-post');
 }finally{app.close()}});
test('visibility, follow access, blocks and comments enforced on server',async()=>{const app=createApp(),a=client(app),b=client(app);try{const au=await account(a,'alice'),bu=await account(b,'bob');const as=fixture('alice'),bs=fixture('bob');as.posts=[post('public'),post('followers','Followers'),post('private','Only me')];await a('/state',{revision:0,data:as},'PUT');await b('/state',{revision:0,data:bs},'PUT');assert.deepEqual((await b('/feed')).body.posts.map(p=>p.id),['public']);bs.follows=[au.id];await b('/state',{revision:1,data:bs},'PUT');assert.equal((await b('/feed')).body.posts.length,2);assert.equal((await b('/comments',{postId:'private',text:'No access'})).status,400);assert.equal((await b('/comments',{postId:'public',text:'Beautiful!'})).status,201);assert.equal((await b('/feed')).body.posts.find(p=>p.id==='public').comments[0].text,'Beautiful!');assert.equal((await a('/feed')).body.ownStats.find(p=>p.id==='public').comments[0].text,'Beautiful!');as.blocked=[bu.id];await a('/state',{revision:1,data:as},'PUT');assert.equal((await b('/feed')).body.posts.length,0);}finally{app.close()}});
test('real conversations, membership, reactions, shares and leaving',async()=>{const app=createApp(),a=client(app),b=client(app),c=client(app);try{await account(a,'alice');await account(b,'bob');await account(c,'charlie');const as=fixture('alice');as.posts=[post('shared-post')];await a('/state',{revision:0,data:as},'PUT');await b('/state',{revision:0,data:fixture('bob')},'PUT');const chat=await a('/conversations',{handle:'bob'});assert.equal(chat.status,201);const cid=chat.body.id;assert.equal((await c('/conversations/'+cid+'/messages',{text:'Intrusion'})).status,403);const sent=await a('/conversations/'+cid+'/messages',{text:'Hello!',postId:'shared-post'});assert.equal(sent.status,201);const received=(await b('/conversations')).body.chats[0];assert.equal(received.messages[0].mine,false);assert.equal(received.messages[0].postId,'shared-post');assert.equal((await b('/messages/'+sent.body.id+'/reaction',{})).status,200);assert.equal((await b('/conversations')).body.chats[0].messages[0].reacted,true);assert.equal((await c('/messages/'+sent.body.id+'/reaction',{})).status,403);await b('/conversations/'+cid+'/leave',{});assert.equal((await b('/conversations')).body.chats.length,0);assert.equal((await b('/conversations/'+cid+'/messages',{text:'After leaving'})).status,403);}finally{app.close()}});
test('private assistant, server-owned approval and no external actions',async()=>{const app=createApp(),a=client(app),b=client(app);try{await account(a,'alice');await account(b,'bob');const r=await a('/assistant',{prompt:'Organise this appointment'});assert.equal(r.body.mode,'demo');assert.ok(r.body.actionId);assert.equal((await b('/assistant')).body.messages.length,0);assert.equal((await b('/actions/'+r.body.actionId+'/approve',{})).status,404);const approved=await a('/actions/'+r.body.actionId+'/approve',{});assert.equal(approved.body.externalAction,false);assert.equal((await a('/assistant')).body.messages.at(-1).approved,true);assert.equal((await a('/feed')).body.posts.length,0);}finally{app.close()}});
test('provider credentials stay server-side; provider failures return safe errors',async()=>{let payload;const app=createApp({apiKey:'test-secret',providerFetch:async(url,options)=>{payload=options;return Response.json({output:[{content:[{type:'output_text',text:'A practical creative idea.'}]}]})}}),a=client(app);try{await account(a,'alice');const r=await a('/assistant',{prompt:'Help with a photo caption'});assert.equal(r.body.mode,'provider');assert.equal(r.body.text,'A practical creative idea.');assert.equal(payload.headers.authorization,'Bearer test-secret');assert.equal(JSON.parse(payload.body).store,false);assert.ok(!JSON.stringify(r.body).includes('test-secret'));}finally{app.close()}});
test('profile and post validation rejects malformed data',async()=>{const app=createApp(),a=client(app);try{await account(a,'alice');const s=fixture('ab');assert.equal((await a('/state',{revision:0,data:s},'PUT')).status,400);s.profile.handle='alice';s.posts=[{...post('unsafe'),media:'javascript:alert(1)'}];assert.equal((await a('/state',{revision:0,data:s},'PUT')).status,400);s.posts=[];assert.equal((await a('/state',{revision:0,data:s},'PUT')).status,200);}finally{app.close()}});
test('database survives restart and password hashes are not returned',async()=>{const {mkdtempSync,rmSync}=await import('node:fs');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const dir=mkdtempSync(join(tmpdir(),'mova-test-')),database=join(dir,'db.sqlite');let app=createApp({database});try{let a=client(app);await account(a,'persistent');await a('/state',{revision:0,data:fixture('persistent')},'PUT');app.close();app=createApp({database});a=client(app);const login=await a('/auth/login',{email:'persistent@example.test',password:'a-strong-test-password'});assert.equal(login.status,200);assert.ok(!JSON.stringify(login.body).includes('salt'));assert.equal((await a('/state')).body.data.profile.handle,'persistent');}finally{app.close();rmSync(dir,{recursive:true,force:true})}});
test('dev origin is explicit and provider errors do not expose credentials',async()=>{const app=createApp({allowedOrigins:['http://localhost:5173'],apiKey:'secret',providerFetch:async()=>Response.json({error:'private provider details'},{status:500})}),a=client(app);try{const registered=await a('/auth/register',{email:'dev@example.test',password:'a-strong-test-password'},'POST','http://localhost:5173');assert.equal(registered.status,200);const r=await a('/assistant',{prompt:'Give me a creative idea'},'POST','http://localhost:5173');assert.equal(r.status,502);assert.ok(!JSON.stringify(r.body).includes('private provider details'));assert.equal((await a('/assistant')).body.messages.length,0);}finally{app.close()}});
